import {
  nativeRustOperationName,
  projectNativeEntityApi,
  toNativeCamelCase,
  toNativePascalCase,
  toNativeScreamingSnakeCase,
  toNativeSnakeCase,
  type NativeEntityModel,
  type NativeOperationParameterModel,
  type NativeProjectedEntityField,
  type NativeSemanticModel,
} from "@tiangz/native-language-core";

export interface NativeGeneratedFile {
  readonly relativePath: string;
  readonly content: string;
  readonly format?: "rust";
}

export interface NativeCodegenOptions {
  readonly generatedBy?: string;
  readonly rustDataPath?: string;
  readonly rustOpsPath?: string;
  readonly bootstrapPath?: string;
  readonly typeScriptRoot?: string;
  readonly componentBaseImport?: string;
  readonly componentDecoratorImport?: string;
  readonly persistenceRuntimeImport?: string;
}

interface ResolvedOptions {
  readonly banner: string;
  readonly rustDataPath: string;
  readonly rustOpsPath: string;
  readonly bootstrapPath: string;
  readonly typeScriptRoot: string;
  readonly componentBaseImport: string;
  readonly componentDecoratorImport: string;
  readonly persistenceRuntimeImport: string;
}

export function generateNativeFiles(
  schema: NativeSemanticModel,
  options: NativeCodegenOptions = {},
): readonly NativeGeneratedFile[] {
  if (schema.operations.length === 0) {
    throw new Error("native codegen needs at least one op declaration");
  }
  const resolved = resolveOptions(options);
  const files: NativeGeneratedFile[] = [
    { relativePath: resolved.rustDataPath, content: renderRust(schema, resolved), format: "rust" },
    { relativePath: resolved.rustOpsPath, content: renderRustOps(schema, resolved), format: "rust" },
    { relativePath: resolved.bootstrapPath, content: renderNativeOpsBootstrap(schema, resolved) },
    {
      relativePath: `${resolved.typeScriptRoot}/NativeOps.ts`,
      content: renderTypeScriptOps(schema, resolved),
    },
  ];
  for (const entity of schema.entities.filter((candidate) => !candidate.abstract)) {
    const api = projectNativeEntityApi(schema, entity);
    files.push({
      relativePath: `${resolved.typeScriptRoot}/${api.fileName}`,
      content: renderTypeScript(schema, entity, resolved),
    });
    if (entity.persistenceVersion !== undefined) {
      files.push({
        relativePath: `${resolved.typeScriptRoot}/Native${entity.name}Persistence.ts`,
        content: renderTypeScriptPersistence(schema, entity, resolved),
      });
    }
  }
  return files;
}

function resolveOptions(options: NativeCodegenOptions): ResolvedOptions {
  const generatedBy = options.generatedBy ?? "tools/codegen_native_data.mjs";
  return {
    banner: `// Generated by ${generatedBy}. Do not edit.`,
    rustDataPath: options.rustDataPath ?? "src/generated/native_data.rs",
    rustOpsPath: options.rustOpsPath ?? "src/generated/native_ops.rs",
    bootstrapPath: options.bootstrapPath ?? "src/generated/native_ops_bootstrap.js",
    typeScriptRoot: options.typeScriptRoot ?? "app/generated/model/native",
    componentBaseImport: options.componentBaseImport ?? "../../../core/runtime/entities",
    componentDecoratorImport: options.componentDecoratorImport ?? "../../../core/runtime/metadata",
    persistenceRuntimeImport: options.persistenceRuntimeImport ?? "../../../core/public",
  };
}

function renderRust(schema: NativeSemanticModel, options: ResolvedOptions): string {
  const entities = schema.entities.map(renderRustStruct).join("\n\n");
  const concrete = schema.entities.filter((entity) => !entity.abstract)
    .sort((left, right) => (left.typeId ?? 0) - (right.typeId ?? 0));
  const splitLayouts = concrete
    .map((entity) => renderRustSplitLayout(schema, entity))
    .filter((layout) => layout.length > 0)
    .join("\n\n");
  const typeConstants = concrete
    .map((entity) => `pub const ENTITY_TYPE_${toNativeScreamingSnakeCase(entity.name)}: u32 = ${entity.typeId};`)
    .join("\n");
  const fieldSections = concrete.map((entity) => renderRustFields(schema, entity)).join("\n\n");
  const variants = concrete.map((entity) => `    ${entity.name}(${entity.name}Data),`).join("\n");
  const typeMatches = concrete
    .map((entity) => `            Self::${entity.name}(_) => ENTITY_TYPE_${toNativeScreamingSnakeCase(entity.name)},`)
    .join("\n");
  const accessors = concrete.map(renderRustVariantAccessors).join("\n");
  const createMatches = concrete.map((entity) => renderRustCreateMatch(schema, entity)).join("\n");
  const getterMatches = concrete
    .map((entity) => `        NativeEntityData::${entity.name}(value) => get_${toNativeSnakeCase(entity.name)}_number(value, field),`)
    .join("\n");
  const setterMatches = concrete
    .map((entity) => `        NativeEntityData::${entity.name}(value) => set_${toNativeSnakeCase(entity.name)}_number(value, field, number),`)
    .join("\n");
  const pools = renderRustPools(schema, concrete);
  return `${options.banner}\n#![allow(dead_code)]\n\n\
${entities}\n\n\
${splitLayouts}${splitLayouts ? "\n\n" : ""}\
${typeConstants}\n\n\
${fieldSections}\n\n\
#[derive(Debug, Clone)]\n\
pub enum NativeEntityData {\n${variants}\n}\n\n\
impl NativeEntityData {\n\
    pub fn type_id(&self) -> u32 {\n\
        match self {\n${typeMatches}\n        }\n\
    }\n\n\
${accessors}\
}\n\n\
pub fn create_entity(type_id: u32, values: &[f64]) -> Result<NativeEntityData, &'static str> {\n\
    match type_id {\n${createMatches}\n        _ => Err("unknown native entity type"),\n\
    }\n\
}\n\n\
pub fn get_entity_number(value: &NativeEntityData, field: u32) -> Option<f64> {\n\
    match value {\n${getterMatches}\n    }\n\
}\n\n\
pub fn set_entity_number(value: &mut NativeEntityData, field: u32, number: f64) -> Result<(), &'static str> {\n\
    match value {\n${setterMatches}\n    }\n\
}\n\n\
${pools}\n\n\
fn read_number(values: &[f64], index: usize) -> Result<f64, &'static str> {\n\
    values.get(index).copied().ok_or("native entity create values are truncated")\n\
}\n\n\
fn read_f32(values: &[f64], index: usize) -> Result<f32, &'static str> {\n\
    let number = read_number(values, index)?;\n\
    if !number.is_finite() || number < f32::MIN as f64 || number > f32::MAX as f64 {\n\
        return Err("native entity create value must be a finite f32");\n\
    }\n\
    Ok(number as f32)\n\
}\n\n\
fn read_u32(values: &[f64], index: usize) -> Result<u32, &'static str> {\n\
    let number = read_number(values, index)?;\n\
    if !number.is_finite() || number.fract() != 0.0 || number < 0.0 || number > u32::MAX as f64 {\n\
        return Err("native entity create value must be u32");\n\
    }\n\
    Ok(number as u32)\n\
}\n\n\
fn read_i32(values: &[f64], index: usize) -> Result<i32, &'static str> {\n\
    let number = read_number(values, index)?;\n\
    if !number.is_finite() || number.fract() != 0.0 || number < i32::MIN as f64 || number > i32::MAX as f64 {\n\
        return Err("native entity create value must be i32");\n\
    }\n\
    Ok(number as i32)\n\
}\n\n\
fn read_i8(values: &[f64], index: usize) -> Result<i8, &'static str> {\n\
    let number = read_number(values, index)?;\n\
    if !number.is_finite() || number.fract() != 0.0 || number < i8::MIN as f64 || number > i8::MAX as f64 {\n\
        return Err("native entity create value must be i8");\n\
    }\n\
    Ok(number as i8)\n\
}\n`;
}

function renderRustOps(schema: NativeSemanticModel, options: ResolvedOptions): string {
  const rustNames = schema.operations.map((operation) => nativeRustOperationName(operation.name));
  return `${options.banner}\n\
use crate::native_data::{${rustNames.join(", ")}};\n\n\
deno_core::extension!(\n\
    native_data_host,\n\
    ops = [\n${rustNames.map((name) => `        ${name},`).join("\n")}\n    ],\n\
);\n\n\
pub(crate) fn init() -> deno_core::Extension {\n\
    native_data_host::init()\n\
}\n\n\
pub(crate) const BOOTSTRAP_SOURCE: &str = include_str!("native_ops_bootstrap.js");\n`;
}

function renderNativeOpsBootstrap(schema: NativeSemanticModel, options: ResolvedOptions): string {
  const methods = schema.operations.map((operation) => {
    const params = operation.params.map((parameter) => parameter.name).join(", ");
    const args = operation.params.map(renderBootstrapArgument).join(", ");
    return `    ${toNativeCamelCase(operation.name)}: (${params}) => core.ops.${nativeRustOperationName(operation.name)}(${args}),`;
  }).join("\n");
  return `${options.banner}\n\
(() => {\n\
  const core = globalThis.Deno.core;\n\
  const integer = (value, min, max, name) => {\n\
    if (!Number.isInteger(value) || value < min || value > max) {\n\
      throw new RangeError(\`native op \${name} must be an integer in [\${min}, \${max}]\`);\n\
    }\n\
    return value;\n\
  };\n\
  const u32 = (value, name) => integer(value, 0, 0xffff_ffff, name);\n\
  const i32 = (value, name) => integer(value, -0x8000_0000, 0x7fff_ffff, name);\n\
  const i64 = (value, name) => {\n\
    if (typeof value !== "bigint" || value < -0x8000_0000_0000_0000n || value > 0x7fff_ffff_ffff_ffffn) {\n\
      throw new RangeError(\`native op \${name} must be an i64 bigint\`);\n\
    }\n\
    return value;\n\
  };\n\
  const i8 = (value, name) => integer(value, -128, 127, name);\n\
  const f64 = (value, name) => {\n\
    if (typeof value !== "number" || !Number.isFinite(value)) {\n\
      throw new TypeError(\`native op \${name} must be a finite number\`);\n\
    }\n\
    return value;\n\
  };\n\
  const f64Array = (value, name) => {\n\
    if (!(value instanceof Float64Array)) {\n\
      throw new TypeError(\`native op \${name} must be Float64Array\`);\n\
    }\n\
    return value;\n\
  };\n\
  const bytes = (value, name) => {\n\
    if (!(value instanceof Uint8Array)) {\n\
      throw new TypeError(\`native op \${name} must be Uint8Array\`);\n\
    }\n\
    return value;\n\
  };\n\
  const bool = (value, name) => {\n\
    if (typeof value !== "boolean") {\n\
      throw new TypeError(\`native op \${name} must be boolean\`);\n\
    }\n\
    return value;\n\
  };\n\
  globalThis.__etsNativeOps = Object.freeze({\n${methods}\n  });\n\
})();\n`;
}

function renderTypeScriptOps(schema: NativeSemanticModel, options: ResolvedOptions): string {
  const interfaceMethods = schema.operations.map((operation) => {
    const params = operation.params.map((parameter) => `${parameter.name}: ${nativeTypeScriptType(parameter.type)}`).join(", ");
    return `  ${toNativeCamelCase(operation.name)}(${params}): ${nativeTypeScriptType(operation.returnType)};`;
  }).join("\n");
  const facadeMethods = schema.operations.map((operation) => {
    const params = operation.params.map((parameter) => `${parameter.name}: ${nativeTypeScriptType(parameter.type)}`).join(", ");
    const args = operation.params.map((parameter) => parameter.name).join(", ");
    const call = `nativeHostOps().${toNativeCamelCase(operation.name)}(${args})`;
    return operation.returnType === "void"
      ? `  static ${operation.name}(${params}): void {\n    ${call};\n  }`
      : `  static ${operation.name}(${params}): ${nativeTypeScriptType(operation.returnType)} {\n    return ${call};\n  }`;
  }).join("\n\n");
  return `${options.banner}\n\n\
export interface NativeHostOpsApi {\n${interfaceMethods}\n}\n\n\
export type NativeRefMetrics = Readonly<Record<string, number>>;\n\n\
function nativeHostOps(): NativeHostOpsApi {\n\
  const host = (globalThis as typeof globalThis & {\n\
    __etsNativeOps?: NativeHostOpsApi;\n\
  }).__etsNativeOps;\n\
  if (!host) throw new Error("native host ops are not installed");\n\
  return host;\n\
}\n\n\
export class NativeOps {\n\
  private static readonly nativeRefCounts = new Map<string, number>();\n\n\
  static TrackNativeRefCreated(entityType: string): void {\n\
    this.nativeRefCounts.set(entityType, (this.nativeRefCounts.get(entityType) ?? 0) + 1);\n\
  }\n\n\
  static TrackNativeRefDestroyed(entityType: string): void {\n\
    const next = (this.nativeRefCounts.get(entityType) ?? 0) - 1;\n\
    if (next < 0) throw new Error("native " + entityType + " ref count became negative");\n\
    if (next === 0) this.nativeRefCounts.delete(entityType);\n\
    else this.nativeRefCounts.set(entityType, next);\n\
  }\n\n\
  static NativeRefMetrics(): NativeRefMetrics {\n\
    return Object.freeze(Object.fromEntries(this.nativeRefCounts));\n\
  }\n\n\
${facadeMethods}\n}\n`;
}

function renderBootstrapArgument(parameter: NativeOperationParameterModel): string {
  const conversions: Record<string, string> = {
    u32: "u32", i32: "i32", i64: "i64", i8: "i8", f64: "f64", "f64[]": "f64Array", bytes: "bytes", bool: "bool",
  };
  const conversion = conversions[parameter.type];
  if (!conversion) throw new Error(`unsupported native parameter type ${parameter.type}`);
  return `${conversion}(${parameter.name}, ${JSON.stringify(parameter.name)})`;
}

function nativeTypeScriptType(type: string): string {
  const types: Record<string, string> = {
    u32: "number", i32: "number", i64: "bigint", i8: "number", f64: "number", "f64[]": "Float64Array",
    bool: "boolean", bytes: "Uint8Array", void: "void",
  };
  const result = types[type];
  if (!result) throw new Error(`unsupported native TypeScript type ${type}`);
  return result;
}

function renderRustStruct(entity: NativeEntityModel): string {
  const rustType: Record<string, string> = { u32: "u32", i32: "i32", i8: "i8", f32: "f32" };
  const parent = entity.parent ? `    pub ${toNativeSnakeCase(entity.parent)}: ${entity.parent}Data,\n` : "";
  const fields = entity.fields.map((field) => {
    const type = rustType[field.type];
    if (!type) throw new Error(`unsupported native Rust field type ${field.type}`);
    return `    pub ${toNativeSnakeCase(field.name)}: ${type},`;
  }).join("\n");
  const dirtyState = entity.replicated
    ? "    pub(crate) __dirty_mask: u64,\n    pub(crate) __revision: u64,\n    pub(crate) __member_revisions: [u64; 64],\n"
    : "";
  return `#[derive(Debug, Clone)]\npub struct ${entity.name}Data {\n${dirtyState}${parent}${fields}\n}`;
}

function renderRustSplitLayout(schema: NativeSemanticModel, entity: NativeEntityModel): string {
  const fields = projectNativeEntityApi(schema, entity).fields;
  if (!fields.some((field) => field.storage !== "default")) return "";
  const hotFields = fields.filter((field) => field.storage === "hot");
  const coldFields = fields.filter((field) => field.storage !== "hot");
  const renderFields = (selected: readonly NativeProjectedEntityField[]) => selected
    .map((field) => `    pub ${toNativeSnakeCase(field.name)}: ${nativeRustFieldType(field.type)},`)
    .join("\n");
  const dirtyState = entity.replicated
    ? "    pub(crate) __dirty_mask: u64,\n    pub(crate) __revision: u64,\n    pub(crate) __member_revisions: [u64; 64],\n"
    : "";
  const hotInit = hotFields
    .map((field) => `            ${toNativeSnakeCase(field.name)}: ${rustFieldPath("value", field)},`)
    .join("\n");
  const coldInit = coldFields
    .map((field) => `            ${toNativeSnakeCase(field.name)}: ${rustFieldPath("value", field)},`)
    .join("\n");
  const dirtyInit = entity.replicated
    ? "            __dirty_mask: value.__dirty_mask,\n            __revision: value.__revision,\n            __member_revisions: value.__member_revisions,\n"
    : "";
  const snakeName = toNativeSnakeCase(entity.name);
  const splitGetters = fields.map((field) =>
    `        ${field.fieldId} => Some(${rustSplitFieldPath("hot", "cold", field)} as f64),`
  ).join("\n");
  const splitSetters = fields.map((field) => field.readonly
    ? `        ${field.fieldId} => Err("native ${entity.name} field ${field.name} is readonly"),`
    : `        ${field.fieldId} => { ${renderRustSplitSetter(entity, field)} Ok(()) },`
  ).join("\n");
  const replicatedFields = fields.filter((field) => field.memberId !== undefined);
  const splitDeltaValues = replicatedFields.map((field) =>
    `        ${toNativeSnakeCase(field.name)}: (dirty_mask & (1u64 << ${field.memberId}) != 0).then_some(${rustSplitFieldPath("hot", "cold", field)}),`
  ).join("\n");
  const splitAckFields = replicatedFields.map((field) =>
    `    if cold.__member_revisions[${field.memberId}] <= revision { cold.__dirty_mask &= !(1u64 << ${field.memberId}); }`
  ).join("\n");
  const splitDirtyAccessors = entity.replicated ? `

pub fn peek_${snakeName}_split_delta(hot: &${entity.name}HotData, cold: &${entity.name}ColdData) -> Option<${entity.name}Delta> {
    let dirty_mask = cold.__dirty_mask;
    if dirty_mask == 0 { return None; }
    Some(${entity.name}Delta {
        revision: cold.__revision,
        dirty_mask,
${splitDeltaValues}
    })
}

pub fn ack_${snakeName}_split_delta(cold: &mut ${entity.name}ColdData, revision: u64) {
${splitAckFields}
}` : "";
  return `#[derive(Debug, Clone)]
pub struct ${entity.name}HotData {
${renderFields(hotFields)}
}

#[derive(Debug, Clone)]
pub struct ${entity.name}ColdData {
${dirtyState}${renderFields(coldFields)}
}

#[derive(Debug, Clone)]
pub struct ${entity.name}SplitData {
    pub hot: ${entity.name}HotData,
    pub cold: ${entity.name}ColdData,
}

impl From<${entity.name}Data> for ${entity.name}SplitData {
    fn from(value: ${entity.name}Data) -> Self {
        Self {
            hot: ${entity.name}HotData {
${hotInit}
            },
            cold: ${entity.name}ColdData {
${dirtyInit}${coldInit}
            },
        }
    }
}

pub fn get_${snakeName}_split_number(hot: &${entity.name}HotData, cold: &${entity.name}ColdData, field: u32) -> Option<f64> {
    match field {
${splitGetters}
        _ => None,
    }
}

pub fn set_${snakeName}_split_number(hot: &mut ${entity.name}HotData, cold: &mut ${entity.name}ColdData, field: u32, number: f64) -> Result<(), &'static str> {
    let _ = (&mut *hot, &mut *cold);
    match field {
${splitSetters}
        _ => Err("unknown native ${entity.name} field"),
    }
}${splitDirtyAccessors}`;
}

function renderRustPools(schema: NativeSemanticModel, entities: readonly NativeEntityModel[]): string {
  const locationVariants = entities.map((entity) => `    ${entity.name}(usize),`).join("\n");
  const poolFields = entities.map((entity) => {
    const snake = toNativeSnakeCase(entity.name);
    if (hasSplitLayout(schema, entity)) {
      return `    ${snake}_hot: Vec<${entity.name}HotData>,\n    ${snake}_cold: Vec<Option<${entity.name}ColdData>>,\n    ${snake}_free: Vec<usize>,`;
    }
    return `    ${snake}_values: Vec<Option<${entity.name}Data>>,\n    ${snake}_free: Vec<usize>,`;
  }).join("\n");
  const insertArms = entities.map((entity) => {
    const snake = toNativeSnakeCase(entity.name);
    if (hasSplitLayout(schema, entity)) {
      return `            NativeEntityData::${entity.name}(value) => {
                let split = ${entity.name}SplitData::from(value);
                let index = if let Some(index) = self.${snake}_free.pop() {
                    self.${snake}_hot[index] = split.hot;
                    self.${snake}_cold[index] = Some(split.cold);
                    index
                } else {
                    let index = self.${snake}_hot.len();
                    self.${snake}_hot.push(split.hot);
                    self.${snake}_cold.push(Some(split.cold));
                    index
                };
                NativePoolLocation::${entity.name}(index)
            }`;
    }
    return `            NativeEntityData::${entity.name}(value) => {
                let index = if let Some(index) = self.${snake}_free.pop() {
                    self.${snake}_values[index] = Some(value);
                    index
                } else {
                    let index = self.${snake}_values.len();
                    self.${snake}_values.push(Some(value));
                    index
                };
                NativePoolLocation::${entity.name}(index)
            }`;
  }).join(",\n");
  const removeArms = entities.map((entity) => {
    const snake = toNativeSnakeCase(entity.name);
    const storage = hasSplitLayout(schema, entity) ? `${snake}_cold` : `${snake}_values`;
    return `            NativePoolLocation::${entity.name}(index) => {
                let removed = self.${storage}.get_mut(index).and_then(Option::take).is_some();
                if removed { self.${snake}_free.push(index); }
                removed
            }`;
  }).join(",\n");
  const getterArms = entities.map((entity) => {
    const snake = toNativeSnakeCase(entity.name);
    if (hasSplitLayout(schema, entity)) {
      return `            NativePoolLocation::${entity.name}(index) => get_${snake}_split_number(
                self.${snake}_hot.get(index)?,
                self.${snake}_cold.get(index)?.as_ref()?,
                field,
            )`;
    }
    return `            NativePoolLocation::${entity.name}(index) => get_${snake}_number(
                self.${snake}_values.get(index)?.as_ref()?,
                field,
            )`;
  }).join(",\n");
  const setterArms = entities.map((entity) => {
    const snake = toNativeSnakeCase(entity.name);
    if (hasSplitLayout(schema, entity)) {
      return `            NativePoolLocation::${entity.name}(index) => {
                let hot = self.${snake}_hot.get_mut(index).ok_or("native pool location is stale")?;
                let cold = self.${snake}_cold.get_mut(index).and_then(Option::as_mut).ok_or("native pool location is stale")?;
                set_${snake}_split_number(hot, cold, field, number)
            }`;
    }
    return `            NativePoolLocation::${entity.name}(index) => set_${snake}_number(
                self.${snake}_values.get_mut(index).and_then(Option::as_mut).ok_or("native pool location is stale")?,
                field,
                number,
            )`;
  }).join(",\n");
  const typedAccessors = entities.map((entity) => renderRustPoolAccessors(schema, entity)).join("\n\n");
  const liveSum = entities.map((entity) => `self.live_${toNativeSnakeCase(entity.name)}()`).join(" + ");
  const capacitySum = entities.map((entity) => {
    const snake = toNativeSnakeCase(entity.name);
    if (hasSplitLayout(schema, entity)) {
      return `self.${snake}_hot.capacity() * std::mem::size_of::<${entity.name}HotData>()
            + self.${snake}_cold.capacity() * std::mem::size_of::<Option<${entity.name}ColdData>>()`;
    }
    return `self.${snake}_values.capacity() * std::mem::size_of::<Option<${entity.name}Data>>()`;
  }).join("\n            + ");
  return `#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum NativePoolLocation {
${locationVariants}
}

#[derive(Default)]
pub struct NativeEntityPools {
${poolFields}
}

impl NativeEntityPools {
    pub fn insert(&mut self, value: NativeEntityData) -> NativePoolLocation {
        match value {
${insertArms}
        }
    }

    pub fn remove(&mut self, location: NativePoolLocation) -> bool {
        match location {
${removeArms}
        }
    }

    pub fn get_number(&self, location: NativePoolLocation, field: u32) -> Option<f64> {
        match location {
${getterArms}
        }
    }

    pub fn set_number(&mut self, location: NativePoolLocation, field: u32, number: f64) -> Result<(), &'static str> {
        match location {
${setterArms}
        }
    }

    pub fn live_entities(&self) -> usize {
        ${liveSum || "0"}
    }

    pub fn estimated_capacity_bytes(&self) -> usize {
        ${capacitySum || "0"}
    }

${typedAccessors}
}`;
}

function renderRustPoolAccessors(schema: NativeSemanticModel, entity: NativeEntityModel): string {
  const snake = toNativeSnakeCase(entity.name);
  if (hasSplitLayout(schema, entity)) {
    return `    pub fn get_${snake}_hot(&self, location: NativePoolLocation) -> Option<&${entity.name}HotData> {
        let NativePoolLocation::${entity.name}(index) = location else { return None; };
        self.${snake}_cold.get(index)?.as_ref()?;
        self.${snake}_hot.get(index)
    }

    pub fn get_${snake}_hot_mut(&mut self, location: NativePoolLocation) -> Option<&mut ${entity.name}HotData> {
        let NativePoolLocation::${entity.name}(index) = location else { return None; };
        self.${snake}_cold.get(index)?.as_ref()?;
        self.${snake}_hot.get_mut(index)
    }

    pub fn get_${snake}_cold(&self, location: NativePoolLocation) -> Option<&${entity.name}ColdData> {
        let NativePoolLocation::${entity.name}(index) = location else { return None; };
        self.${snake}_cold.get(index)?.as_ref()
    }

    pub fn get_${snake}_cold_mut(&mut self, location: NativePoolLocation) -> Option<&mut ${entity.name}ColdData> {
        let NativePoolLocation::${entity.name}(index) = location else { return None; };
        self.${snake}_cold.get_mut(index)?.as_mut()
    }

    pub fn get_${snake}_parts(&self, location: NativePoolLocation) -> Option<(&${entity.name}HotData, &${entity.name}ColdData)> {
        let NativePoolLocation::${entity.name}(index) = location else { return None; };
        Some((self.${snake}_hot.get(index)?, self.${snake}_cold.get(index)?.as_ref()?))
    }

    pub fn get_${snake}_parts_mut(&mut self, location: NativePoolLocation) -> Option<(&mut ${entity.name}HotData, &mut ${entity.name}ColdData)> {
        let NativePoolLocation::${entity.name}(index) = location else { return None; };
        Some((self.${snake}_hot.get_mut(index)?, self.${snake}_cold.get_mut(index)?.as_mut()?))
    }

    pub fn live_${snake}(&self) -> usize {
        self.${snake}_cold.len() - self.${snake}_free.len()
    }`;
  }
  return `    pub fn get_${snake}(&self, location: NativePoolLocation) -> Option<&${entity.name}Data> {
        let NativePoolLocation::${entity.name}(index) = location else { return None; };
        self.${snake}_values.get(index)?.as_ref()
    }

    pub fn get_${snake}_mut(&mut self, location: NativePoolLocation) -> Option<&mut ${entity.name}Data> {
        let NativePoolLocation::${entity.name}(index) = location else { return None; };
        self.${snake}_values.get_mut(index)?.as_mut()
    }

    pub fn live_${snake}(&self) -> usize {
        self.${snake}_values.len() - self.${snake}_free.len()
    }`;
}

function hasSplitLayout(schema: NativeSemanticModel, entity: NativeEntityModel): boolean {
  return projectNativeEntityApi(schema, entity).fields.some((field) => field.storage !== "default");
}

function renderRustFields(schema: NativeSemanticModel, entity: NativeEntityModel): string {
  const fields = projectNativeEntityApi(schema, entity).fields;
  const snakeName = toNativeSnakeCase(entity.name);
  const constants = fields.map((field) => `pub const ${field.rustFieldConstant}: u32 = ${field.fieldId};`).join("\n");
  const memberConstants = fields.filter((field) => field.memberId !== undefined)
    .map((field) => `pub const ${toNativeScreamingSnakeCase(entity.name)}_MEMBER_${toNativeScreamingSnakeCase(field.name)}: u32 = ${field.memberId};`).join("\n");
  const getters = fields.map((field) => `        ${field.fieldId} => Some(${rustFieldPath("value", field)} as f64),`).join("\n");
  const setters = fields.map((field) => field.readonly
    ? `        ${field.fieldId} => Err("native ${entity.name} field ${field.name} is readonly"),`
    : `        ${field.fieldId} => { ${renderRustSetter(entity, field)} Ok(()) },`).join("\n");
  const replicatedFields = fields.filter((field) => field.memberId !== undefined);
  const deltaFields = replicatedFields.map((field) => `    pub ${toNativeSnakeCase(field.name)}: Option<${nativeRustFieldType(field.type)}>,`).join("\n");
  const deltaValues = replicatedFields.map((field) => `        ${toNativeSnakeCase(field.name)}: (dirty_mask & (1u64 << ${field.memberId}) != 0).then_some(${rustFieldPath("value", field)}),`).join("\n");
  const ackFields = replicatedFields.map((field) => `    if value.__member_revisions[${field.memberId}] <= revision { value.__dirty_mask &= !(1u64 << ${field.memberId}); }`).join("\n");
  const dirtyAccessors = entity.replicated ? `\n\n#[derive(Debug, Clone, PartialEq)]\npub struct ${entity.name}Delta {\n    pub revision: u64,\n    pub dirty_mask: u64,\n${deltaFields}\n}\n\npub fn ${snakeName}_dirty_mask(value: &${entity.name}Data) -> u64 { value.__dirty_mask }\n\npub fn peek_${snakeName}_delta(value: &${entity.name}Data) -> Option<${entity.name}Delta> {\n    let dirty_mask = value.__dirty_mask;\n    if dirty_mask == 0 { return None; }\n    Some(${entity.name}Delta {\n        revision: value.__revision,\n        dirty_mask,\n${deltaValues}\n    })\n}\n\npub fn ack_${snakeName}_delta(value: &mut ${entity.name}Data, revision: u64) {\n${ackFields}\n}` : "";
  return `${constants}${memberConstants ? `\n${memberConstants}` : ""}\n\n\
pub fn get_${snakeName}_number(value: &${entity.name}Data, field: u32) -> Option<f64> {\n\
    match field {\n${getters}\n        _ => None,\n    }\n\
}\n\n\
pub fn set_${snakeName}_number(value: &mut ${entity.name}Data, field: u32, number: f64) -> Result<(), &'static str> {\n\
    match field {\n${setters}\n        _ => Err("unknown native ${entity.name} field"),\n    }\n\
}${dirtyAccessors}`;
}

function renderRustVariantAccessors(entity: NativeEntityModel): string {
  const snake = toNativeSnakeCase(entity.name);
  return `    pub fn as_${snake}(&self) -> Option<&${entity.name}Data> {\n\
        match self { Self::${entity.name}(value) => Some(value), _ => None }\n\
    }\n\n\
    pub fn as_${snake}_mut(&mut self) -> Option<&mut ${entity.name}Data> {\n\
        match self { Self::${entity.name}(value) => Some(value), _ => None }\n\
    }\n`;
}

function renderRustCreateMatch(schema: NativeSemanticModel, entity: NativeEntityModel): string {
  const fields = projectNativeEntityApi(schema, entity).fields;
  const values = new Map(fields.map((field, index) => [field.name, `read_${field.type}(values, ${index})?`]));
  const init = renderRustStructInit(schema, entity.name, values, 12);
  return `        ENTITY_TYPE_${toNativeScreamingSnakeCase(entity.name)} => {\n\
            if values.len() != ${fields.length} { return Err("native ${entity.name} create value count mismatch"); }\n\
            if read_u32(values, 0)? == 0 || read_u32(values, 1)? == 0 {\n\
                return Err("native Entity id and instanceId must be greater than zero");\n\
            }\n\
            Ok(NativeEntityData::${entity.name}(${init}))\n\
        },`;
}

function renderRustStructInit(
  schema: NativeSemanticModel,
  entityName: string,
  values: ReadonlyMap<string, string>,
  indent: number,
): string {
  const entity = schema.entities.find((candidate) => candidate.name === entityName);
  if (!entity) throw new Error(`unknown native entity ${entityName}`);
  const padding = " ".repeat(indent);
  const childPadding = " ".repeat(indent + 4);
  const lines: string[] = [];
  if (entity.replicated) {
    lines.push(`${childPadding}__dirty_mask: 0u64,`);
    lines.push(`${childPadding}__revision: 0u64,`);
    lines.push(`${childPadding}__member_revisions: [0u64; 64],`);
  }
  if (entity.parent) {
    lines.push(`${childPadding}${toNativeSnakeCase(entity.parent)}: ${renderRustStructInit(schema, entity.parent, values, indent + 4)},`);
  }
  for (const field of entity.fields) {
    lines.push(`${childPadding}${toNativeSnakeCase(field.name)}: ${values.get(field.name)},`);
  }
  return `${entity.name}Data {\n${lines.join("\n")}\n${padding}}`;
}

function renderTypeScript(schema: NativeSemanticModel, entity: NativeEntityModel, options: ResolvedOptions): string {
  const api = projectNativeEntityApi(schema, entity);
  const fields = api.fields;
  const fieldConstants = fields.filter((field) => field.ownerName === entity.name)
    .map((field) => `  ${toNativePascalCase(field.name)}: ${field.fieldId},`).join("\n");
  const fieldTypes = `export const ${api.fieldTableName} = {\n${fieldConstants}\n} as const;\n\nexport type ${api.fieldTableName} = typeof ${api.fieldTableName}[keyof typeof ${api.fieldTableName}];`;
  const memberConstants = fields.filter((field) => field.ownerName === entity.name && field.memberId !== undefined)
    .map((field) => `  ${toNativePascalCase(field.name)}: ${field.memberId},`).join("\n");
  const memberTypes = memberConstants ? `\n\nexport const Native${entity.name}Member = {\n${memberConstants}\n} as const;\n\nexport type Native${entity.name}Member = typeof Native${entity.name}Member[keyof typeof Native${entity.name}Member];` : "";
  const args = fields.map((field) => `  ${field.name}${field.defaultValue === undefined ? "" : "?"}: number;`).join("\n");
  const values = fields.map((field) => field.defaultValue === undefined
    ? `      args.${field.name},`
    : `      args.${field.name} ?? ${field.defaultValue},`).join("\n");
  const properties = fields.map((field) => {
    const setter = field.readonly ? "" : `\n  set ${field.name}(value: number) {\n    NativeOps.EntitySetNumber(this.Handle, ${field.fieldId}, value);\n  }\n`;
    return `  get ${field.name}(): number {\n    return NativeOps.EntityGetNumber(this.Handle, ${field.fieldId});\n  }\n${setter}`;
  }).join("\n");
  if (api.lifecycle === "handle") {
    return renderTypeScriptHandle(entity, api, args, values, properties, fieldTypes + memberTypes, options);
  }
  return `${options.banner}\n\n\
import { NativeOps } from "./NativeOps";\n\
import { Component } from "${options.componentBaseImport}";\n\
import { component } from "${options.componentDecoratorImport}";\n\n\
${fieldTypes}${memberTypes}\n\n\
export interface ${api.createArgsName} {\n${args}\n}\n\n\
@component()\n\
export class ${api.refName} extends Component<[args: ${api.createArgsName}]> {\n\
  private nativeHandle = 0;\n\n\
  get Handle(): number {\n\
    if (this.nativeHandle === 0) throw new Error("native ${entity.name} handle is not alive");\n\
    return this.nativeHandle;\n\
  }\n\n\
  protected override Awake(args: ${api.createArgsName}): void {\n\
    this.nativeHandle = NativeOps.EntityCreate(${entity.typeId}, new Float64Array([\n${values}\n    ]));\n\
    NativeOps.TrackNativeRefCreated("${entity.name}");\n\
  }\n\n\
${properties}\
  protected override OnDestroy(): void {\n\
    if (this.nativeHandle === 0) return;\n\
    NativeOps.EntityDestroy(this.nativeHandle);\n\
    this.nativeHandle = 0;\n\
    NativeOps.TrackNativeRefDestroyed("${entity.name}");\n\
  }\n\
}\n`;
}

function renderTypeScriptHandle(
  entity: NativeEntityModel,
  api: ReturnType<typeof projectNativeEntityApi>,
  args: string,
  values: string,
  properties: string,
  fieldTypes: string,
  options: ResolvedOptions,
): string {
  return `${options.banner}\n\n\
import { NativeOps } from "./NativeOps";\n\n\
${fieldTypes}\n\n\
export class ${api.refName} {\n\
  private nativeHandle: number;\n\n\
  private constructor(handle: number) {\n\
    this.nativeHandle = handle;\n\
    NativeOps.TrackNativeRefCreated("${entity.name}");\n\
  }\n\n\
  static Create(args: ${api.createArgsName}): ${api.refName} {\n\
    return new ${api.refName}(NativeOps.EntityCreate(${entity.typeId}, new Float64Array([\n${values}\n    ])));\n\
  }\n\n\
  get Handle(): number {\n\
    if (this.nativeHandle === 0) throw new Error("native ${entity.name} handle is not alive");\n\
    return this.nativeHandle;\n\
  }\n\n\
${properties}\n\
  Dispose(): void {\n\
    if (this.nativeHandle === 0) return;\n\
    NativeOps.EntityDestroy(this.nativeHandle);\n\
    this.nativeHandle = 0;\n\
    NativeOps.TrackNativeRefDestroyed("${entity.name}");\n\
  }\n\
}\n\n\
export interface ${api.createArgsName} {\n${args}\n}\n`;
}

function renderTypeScriptPersistence(
  schema: NativeSemanticModel,
  entity: NativeEntityModel,
  options: ResolvedOptions,
): string {
  const version = entity.persistenceVersion;
  if (version === undefined) throw new Error(`native entity ${entity.name} is not persistent`);
  const api = projectNativeEntityApi(schema, entity);
  const fields = api.fields.filter((field) => !field.transient);
  if (fields.length === 0) throw new Error(`persistent native entity ${entity.name} has no persisted fields`);
  const snapshotName = `Native${entity.name}PersistenceSnapshot`;
  const codecName = `Native${entity.name}PersistenceCodec`;
  const properties = fields.map((field) => `  readonly ${field.name}: number;`).join("\n");
  const captures = fields.map((field) => `      ${field.name}: value.${field.name},`).join("\n");
  const validations = fields.map((field) => renderTypeScriptPersistenceValidation(field)).join("\n");
  const fieldNames = fields.map((field) => `"${field.name}"`).join(", ");
  const schemaName = `${entity.namespace}.${entity.name}`;
  const recordNamespace = `entity.${entity.namespace}.${toNativeSnakeCase(entity.name)}`.toLowerCase();
  return `${options.banner}\n\n\
import { DbProxyEntityRepository, utf8Decode, utf8Encode, type VersionedEntityCodec } from "${options.persistenceRuntimeImport}";\n\
import { ${api.refName} } from "./${api.fileName.replace(/\.ts$/, "")}";\n\n\
export interface ${snapshotName} {\n${properties}\n}\n\n\
/** 由.native版本化结构生成；DBProxy只保存其不透明字节。 / Generated from the versioned .native shape; DBProxy stores only opaque bytes. */\n\
export const ${codecName}: VersionedEntityCodec<${snapshotName}, ${api.refName}> = {\n\
  recordNamespace: "${recordNamespace}",\n\
  schema: "${schemaName}",\n\
  schemaVersion: ${version},\n\n\
  Capture(value: ${api.refName}): ${snapshotName} {\n\
    return {\n${captures}\n    };\n\
  },\n\n\
  Encode(value: ${snapshotName}): Uint8Array {\n\
    validateSnapshot(value);\n\
    return utf8Encode(JSON.stringify({ version: ${version}, data: value }));\n\
  },\n\n\
  Decode(payload: Uint8Array): ${snapshotName} {\n\
    let decoded: unknown;\n\
    try { decoded = JSON.parse(utf8Decode(payload)); }\n\
    catch (error) { throw new Error(\`invalid ${schemaName} persistence payload: \${String(error)}\`); }\n\
    const envelope = requireRecord(decoded, "payload");\n\
    if (envelope.version !== ${version}) throw new Error(\`unsupported ${schemaName} persistence version: \${String(envelope.version)}\`);\n\
    validateSnapshot(envelope.data);\n\
    return envelope.data;\n\
  },\n\
};\n\n\
/** 创建该Entity的通用DBProxy Repository；复杂查询和跨记录事务应另写领域Repository。 / Creates the generic DBProxy Repository; queries and cross-record transactions need a domain Repository. */\n\
export function CreateNative${entity.name}Repository(processName: string): DbProxyEntityRepository<${snapshotName}, ${api.refName}> {\n\
  return new DbProxyEntityRepository(${codecName}, processName);\n\
}\n\n\
function validateSnapshot(value: unknown): asserts value is ${snapshotName} {\n\
  const record = requireRecord(value, "${schemaName}");\n\
  const allowed = new Set([${fieldNames}]);\n\
  for (const key of Object.keys(record)) {\n\
    if (!allowed.has(key)) throw new TypeError(\`${schemaName}.\${key} is unknown\`);\n\
  }\n\
  if (Object.keys(record).length !== allowed.size) throw new TypeError("${schemaName} persistence fields are incomplete");\n\
${validations}\n\
}\n\n\
function requireRecord(value: unknown, name: string): Record<string, unknown> {\n\
  if (typeof value !== "object" || value === null || Array.isArray(value)) throw new TypeError(\`\${name} must be an object\`);\n\
  return value as Record<string, unknown>;\n\
}\n`;
}

function renderTypeScriptPersistenceValidation(field: NativeProjectedEntityField): string {
  const value = `record.${field.name}`;
  if (field.type === "f32") {
    return `  if (typeof ${value} !== "number" || !Number.isFinite(${value}) || Math.abs(${value}) > 3.4028234663852886e38) throw new TypeError("${field.name} must be a finite f32");`;
  }
  const ranges: Record<string, readonly [number, number]> = {
    u32: [0, 0xffff_ffff],
    i32: [-0x8000_0000, 0x7fff_ffff],
    i8: [-128, 127],
  };
  const range = ranges[field.type];
  if (!range) throw new Error(`unsupported persistence field type ${field.type}`);
  return `  if (typeof ${value} !== "number" || !Number.isSafeInteger(${value}) || ${value} < ${range[0]} || ${value} > ${range[1]}) throw new TypeError("${field.name} must be ${field.type}");`;
}

function rustFieldPath(root: string, field: NativeProjectedEntityField): string {
  return `${root}.${field.rustPath.join(".")}`;
}

function renderRustSetter(entity: NativeEntityModel, field: NativeProjectedEntityField): string {
  const target = rustFieldPath("value", field);
  return renderRustSetterForTarget(entity, field, target, "value");
}

function renderRustSplitSetter(entity: NativeEntityModel, field: NativeProjectedEntityField): string {
  return renderRustSetterForTarget(entity, field, rustSplitFieldPath("hot", "cold", field), "cold");
}

function renderRustSetterForTarget(
  entity: NativeEntityModel,
  field: NativeProjectedEntityField,
  target: string,
  dirtyRoot: string,
): string {
  if (field.type === "f32") {
    return wrapDirtyAssignment(entity, field, target, dirtyRoot, `number as f32`, `if !number.is_finite() || number < f32::MIN as f64 || number > f32::MAX as f64 { return Err("native ${entity.name} field ${field.name} must be a finite f32"); }`);
  }
  const ranges: Record<string, readonly [string, string, string]> = {
    u32: ["0.0", "u32::MAX as f64", "u32"],
    i32: ["i32::MIN as f64", "i32::MAX as f64", "i32"],
    i8: ["i8::MIN as f64", "i8::MAX as f64", "i8"],
  };
  const range = ranges[field.type];
  if (!range) throw new Error(`unsupported native setter field type ${field.type}`);
  const [min, max, type] = range;
  return wrapDirtyAssignment(entity, field, target, dirtyRoot, `number as ${type}`, `if !number.is_finite() || number.fract() != 0.0 || number < ${min} || number > ${max} { return Err("native ${entity.name} field ${field.name} must be ${field.type}"); }`);
}

function nativeRustFieldType(type: NativeProjectedEntityField["type"]): string {
  const types: Record<NativeProjectedEntityField["type"], string> = {
    u32: "u32",
    i32: "i32",
    i8: "i8",
    f32: "f32",
  };
  const result = types[type];
  if (!result) throw new Error(`unsupported native Rust field type ${type}`);
  return result;
}

function wrapDirtyAssignment(entity: NativeEntityModel, field: NativeProjectedEntityField, target: string, dirtyRoot: string, converted: string, validation: string): string {
  const assign = field.memberId === undefined
    ? `${target} = converted;`
    : `if ${target} != converted { ${target} = converted; ${dirtyRoot}.__revision = ${dirtyRoot}.__revision.wrapping_add(1).max(1); ${dirtyRoot}.__member_revisions[${field.memberId}] = ${dirtyRoot}.__revision; ${dirtyRoot}.__dirty_mask |= 1u64 << ${field.memberId}; }`;
  return `${validation} let converted = ${converted}; ${assign}`;
}

function rustSplitFieldPath(hotRoot: string, coldRoot: string, field: NativeProjectedEntityField): string {
  return `${field.storage === "hot" ? hotRoot : coldRoot}.${toNativeSnakeCase(field.name)}`;
}
