import {
  nativeRustOperationName,
  projectNativeEntityApi,
  toNativeCamelCase,
  toNativePascalCase,
  toNativeScreamingSnakeCase,
  toNativeSnakeCase,
  type NativeEntityModel,
  type NativeOperationParameterModel,
  type NativeProjectedEntityField,
  type NativeSemanticModel,
} from "@tiangz/native-language-core";

export interface NativeGeneratedFile {
  readonly relativePath: string;
  readonly content: string;
  readonly format?: "rust";
}

export interface NativeCodegenOptions {
  readonly generatedBy?: string;
  readonly rustDataPath?: string;
  readonly rustOpsPath?: string;
  readonly bootstrapPath?: string;
  readonly typeScriptRoot?: string;
  readonly componentBaseImport?: string;
  readonly componentDecoratorImport?: string;
}

interface ResolvedOptions {
  readonly banner: string;
  readonly rustDataPath: string;
  readonly rustOpsPath: string;
  readonly bootstrapPath: string;
  readonly typeScriptRoot: string;
  readonly componentBaseImport: string;
  readonly componentDecoratorImport: string;
}

export function generateNativeFiles(
  schema: NativeSemanticModel,
  options: NativeCodegenOptions = {},
): readonly NativeGeneratedFile[] {
  if (schema.operations.length === 0) {
    throw new Error("native codegen needs at least one op declaration");
  }
  const resolved = resolveOptions(options);
  const files: NativeGeneratedFile[] = [
    { relativePath: resolved.rustDataPath, content: renderRust(schema, resolved), format: "rust" },
    { relativePath: resolved.rustOpsPath, content: renderRustOps(schema, resolved), format: "rust" },
    { relativePath: resolved.bootstrapPath, content: renderNativeOpsBootstrap(schema, resolved) },
    {
      relativePath: `${resolved.typeScriptRoot}/NativeOps.ts`,
      content: renderTypeScriptOps(schema, resolved),
    },
  ];
  for (const entity of schema.entities.filter((candidate) => !candidate.abstract)) {
    const api = projectNativeEntityApi(schema, entity);
    files.push({
      relativePath: `${resolved.typeScriptRoot}/${api.fileName}`,
      content: renderTypeScript(schema, entity, resolved),
    });
  }
  return files;
}

function resolveOptions(options: NativeCodegenOptions): ResolvedOptions {
  const generatedBy = options.generatedBy ?? "tools/codegen_native_data.mjs";
  return {
    banner: `// Generated by ${generatedBy}. Do not edit.`,
    rustDataPath: options.rustDataPath ?? "src/generated/native_data.rs",
    rustOpsPath: options.rustOpsPath ?? "src/generated/native_ops.rs",
    bootstrapPath: options.bootstrapPath ?? "src/generated/native_ops_bootstrap.js",
    typeScriptRoot: options.typeScriptRoot ?? "app/generated/model/native",
    componentBaseImport: options.componentBaseImport ?? "../../../core/runtime/entities",
    componentDecoratorImport: options.componentDecoratorImport ?? "../../../core/runtime/metadata",
  };
}

function renderRust(schema: NativeSemanticModel, options: ResolvedOptions): string {
  const entities = schema.entities.map(renderRustStruct).join("\n\n");
  const concrete = schema.entities.filter((entity) => !entity.abstract)
    .sort((left, right) => (left.typeId ?? 0) - (right.typeId ?? 0));
  const typeConstants = concrete
    .map((entity) => `pub const ENTITY_TYPE_${toNativeScreamingSnakeCase(entity.name)}: u32 = ${entity.typeId};`)
    .join("\n");
  const fieldSections = concrete.map((entity) => renderRustFields(schema, entity)).join("\n\n");
  const variants = concrete.map((entity) => `    ${entity.name}(${entity.name}Data),`).join("\n");
  const typeMatches = concrete
    .map((entity) => `            Self::${entity.name}(_) => ENTITY_TYPE_${toNativeScreamingSnakeCase(entity.name)},`)
    .join("\n");
  const accessors = concrete.map(renderRustVariantAccessors).join("\n");
  const createMatches = concrete.map((entity) => renderRustCreateMatch(schema, entity)).join("\n");
  const getterMatches = concrete
    .map((entity) => `        NativeEntityData::${entity.name}(value) => get_${toNativeSnakeCase(entity.name)}_number(value, field),`)
    .join("\n");
  const setterMatches = concrete
    .map((entity) => `        NativeEntityData::${entity.name}(value) => set_${toNativeSnakeCase(entity.name)}_number(value, field, number),`)
    .join("\n");
  return `${options.banner}\n#![allow(dead_code)]\n\n\
${entities}\n\n\
${typeConstants}\n\n\
${fieldSections}\n\n\
#[derive(Debug, Clone)]\n\
pub enum NativeEntityData {\n${variants}\n}\n\n\
impl NativeEntityData {\n\
    pub fn type_id(&self) -> u32 {\n\
        match self {\n${typeMatches}\n        }\n\
    }\n\n\
${accessors}\
}\n\n\
pub fn create_entity(type_id: u32, values: &[f64]) -> Result<NativeEntityData, &'static str> {\n\
    match type_id {\n${createMatches}\n        _ => Err("unknown native entity type"),\n\
    }\n\
}\n\n\
pub fn get_entity_number(value: &NativeEntityData, field: u32) -> Option<f64> {\n\
    match value {\n${getterMatches}\n    }\n\
}\n\n\
pub fn set_entity_number(value: &mut NativeEntityData, field: u32, number: f64) -> Result<(), &'static str> {\n\
    match value {\n${setterMatches}\n    }\n\
}\n\n\
fn read_number(values: &[f64], index: usize) -> Result<f64, &'static str> {\n\
    values.get(index).copied().ok_or("native entity create values are truncated")\n\
}\n\n\
fn read_f32(values: &[f64], index: usize) -> Result<f32, &'static str> {\n\
    let number = read_number(values, index)?;\n\
    if !number.is_finite() || number < f32::MIN as f64 || number > f32::MAX as f64 {\n\
        return Err("native entity create value must be a finite f32");\n\
    }\n\
    Ok(number as f32)\n\
}\n\n\
fn read_u32(values: &[f64], index: usize) -> Result<u32, &'static str> {\n\
    let number = read_number(values, index)?;\n\
    if !number.is_finite() || number.fract() != 0.0 || number < 0.0 || number > u32::MAX as f64 {\n\
        return Err("native entity create value must be u32");\n\
    }\n\
    Ok(number as u32)\n\
}\n\n\
fn read_i32(values: &[f64], index: usize) -> Result<i32, &'static str> {\n\
    let number = read_number(values, index)?;\n\
    if !number.is_finite() || number.fract() != 0.0 || number < i32::MIN as f64 || number > i32::MAX as f64 {\n\
        return Err("native entity create value must be i32");\n\
    }\n\
    Ok(number as i32)\n\
}\n\n\
fn read_i8(values: &[f64], index: usize) -> Result<i8, &'static str> {\n\
    let number = read_number(values, index)?;\n\
    if !number.is_finite() || number.fract() != 0.0 || number < i8::MIN as f64 || number > i8::MAX as f64 {\n\
        return Err("native entity create value must be i8");\n\
    }\n\
    Ok(number as i8)\n\
}\n`;
}

function renderRustOps(schema: NativeSemanticModel, options: ResolvedOptions): string {
  const rustNames = schema.operations.map((operation) => nativeRustOperationName(operation.name));
  return `${options.banner}\n\
use crate::native_data::{${rustNames.join(", ")}};\n\n\
deno_core::extension!(\n\
    native_data_host,\n\
    ops = [\n${rustNames.map((name) => `        ${name},`).join("\n")}\n    ],\n\
);\n\n\
pub(crate) fn init() -> deno_core::Extension {\n\
    native_data_host::init()\n\
}\n\n\
pub(crate) const BOOTSTRAP_SOURCE: &str = include_str!("native_ops_bootstrap.js");\n`;
}

function renderNativeOpsBootstrap(schema: NativeSemanticModel, options: ResolvedOptions): string {
  const methods = schema.operations.map((operation) => {
    const params = operation.params.map((parameter) => parameter.name).join(", ");
    const args = operation.params.map(renderBootstrapArgument).join(", ");
    return `    ${toNativeCamelCase(operation.name)}: (${params}) => core.ops.${nativeRustOperationName(operation.name)}(${args}),`;
  }).join("\n");
  return `${options.banner}\n\
(() => {\n\
  const core = globalThis.Deno.core;\n\
  const integer = (value, min, max, name) => {\n\
    if (!Number.isInteger(value) || value < min || value > max) {\n\
      throw new RangeError(\`native op \${name} must be an integer in [\${min}, \${max}]\`);\n\
    }\n\
    return value;\n\
  };\n\
  const u32 = (value, name) => integer(value, 0, 0xffff_ffff, name);\n\
  const i32 = (value, name) => integer(value, -0x8000_0000, 0x7fff_ffff, name);\n\
  const i8 = (value, name) => integer(value, -128, 127, name);\n\
  const f64 = (value, name) => {\n\
    if (typeof value !== "number" || !Number.isFinite(value)) {\n\
      throw new TypeError(\`native op \${name} must be a finite number\`);\n\
    }\n\
    return value;\n\
  };\n\
  const f64Array = (value, name) => {\n\
    if (!(value instanceof Float64Array)) {\n\
      throw new TypeError(\`native op \${name} must be Float64Array\`);\n\
    }\n\
    return value;\n\
  };\n\
  const bytes = (value, name) => {\n\
    if (!(value instanceof Uint8Array)) {\n\
      throw new TypeError(\`native op \${name} must be Uint8Array\`);\n\
    }\n\
    return value;\n\
  };\n\
  const bool = (value, name) => {\n\
    if (typeof value !== "boolean") {\n\
      throw new TypeError(\`native op \${name} must be boolean\`);\n\
    }\n\
    return value;\n\
  };\n\
  globalThis.__etsNativeOps = Object.freeze({\n${methods}\n  });\n\
})();\n`;
}

function renderTypeScriptOps(schema: NativeSemanticModel, options: ResolvedOptions): string {
  const interfaceMethods = schema.operations.map((operation) => {
    const params = operation.params.map((parameter) => `${parameter.name}: ${nativeTypeScriptType(parameter.type)}`).join(", ");
    return `  ${toNativeCamelCase(operation.name)}(${params}): ${nativeTypeScriptType(operation.returnType)};`;
  }).join("\n");
  const facadeMethods = schema.operations.map((operation) => {
    const params = operation.params.map((parameter) => `${parameter.name}: ${nativeTypeScriptType(parameter.type)}`).join(", ");
    const args = operation.params.map((parameter) => parameter.name).join(", ");
    const call = `nativeHostOps().${toNativeCamelCase(operation.name)}(${args})`;
    return operation.returnType === "void"
      ? `  static ${operation.name}(${params}): void {\n    ${call};\n  }`
      : `  static ${operation.name}(${params}): ${nativeTypeScriptType(operation.returnType)} {\n    return ${call};\n  }`;
  }).join("\n\n");
  return `${options.banner}\n\n\
export interface NativeHostOpsApi {\n${interfaceMethods}\n}\n\n\
function nativeHostOps(): NativeHostOpsApi {\n\
  const host = (globalThis as typeof globalThis & {\n\
    __etsNativeOps?: NativeHostOpsApi;\n\
  }).__etsNativeOps;\n\
  if (!host) throw new Error("native host ops are not installed");\n\
  return host;\n\
}\n\n\
export class NativeOps {\n${facadeMethods}\n}\n`;
}

function renderBootstrapArgument(parameter: NativeOperationParameterModel): string {
  const conversions: Record<string, string> = {
    u32: "u32", i32: "i32", i8: "i8", f64: "f64", "f64[]": "f64Array", bytes: "bytes", bool: "bool",
  };
  const conversion = conversions[parameter.type];
  if (!conversion) throw new Error(`unsupported native parameter type ${parameter.type}`);
  return `${conversion}(${parameter.name}, ${JSON.stringify(parameter.name)})`;
}

function nativeTypeScriptType(type: string): string {
  const types: Record<string, string> = {
    u32: "number", i32: "number", i8: "number", f64: "number", "f64[]": "Float64Array",
    bool: "boolean", bytes: "Uint8Array", void: "void",
  };
  const result = types[type];
  if (!result) throw new Error(`unsupported native TypeScript type ${type}`);
  return result;
}

function renderRustStruct(entity: NativeEntityModel): string {
  const rustType: Record<string, string> = { u32: "u32", i32: "i32", i8: "i8", f32: "f32" };
  const parent = entity.parent ? `    pub ${toNativeSnakeCase(entity.parent)}: ${entity.parent}Data,\n` : "";
  const fields = entity.fields.map((field) => {
    const type = rustType[field.type];
    if (!type) throw new Error(`unsupported native Rust field type ${field.type}`);
    return `    pub ${toNativeSnakeCase(field.name)}: ${type},`;
  }).join("\n");
  const dirtyMask = entity.replicated ? "    pub(crate) __dirty_mask: u64,\n" : "";
  return `#[derive(Debug, Clone)]\npub struct ${entity.name}Data {\n${dirtyMask}${parent}${fields}\n}`;
}

function renderRustFields(schema: NativeSemanticModel, entity: NativeEntityModel): string {
  const fields = projectNativeEntityApi(schema, entity).fields;
  const snakeName = toNativeSnakeCase(entity.name);
  const constants = fields.map((field) => `pub const ${field.rustFieldConstant}: u32 = ${field.fieldId};`).join("\n");
  const memberConstants = fields.filter((field) => field.memberId !== undefined)
    .map((field) => `pub const ${toNativeScreamingSnakeCase(entity.name)}_MEMBER_${toNativeScreamingSnakeCase(field.name)}: u32 = ${field.memberId};`).join("\n");
  const getters = fields.map((field) => `        ${field.fieldId} => Some(${rustFieldPath("value", field)} as f64),`).join("\n");
  const setters = fields.map((field) => field.readonly
    ? `        ${field.fieldId} => Err("native ${entity.name} field ${field.name} is readonly"),`
    : `        ${field.fieldId} => { ${renderRustSetter(entity, field)} Ok(()) },`).join("\n");
  const replicatedFields = fields.filter((field) => field.memberId !== undefined);
  const deltaFields = replicatedFields.map((field) => `    pub ${toNativeSnakeCase(field.name)}: Option<${nativeRustFieldType(field.type)}>,`).join("\n");
  const deltaValues = replicatedFields.map((field) => `        ${toNativeSnakeCase(field.name)}: (dirty_mask & (1u64 << ${field.memberId}) != 0).then_some(${rustFieldPath("value", field)}),`).join("\n");
  const dirtyAccessors = entity.replicated ? `\n\n#[derive(Debug, Clone, PartialEq)]\npub struct ${entity.name}Delta {\n    pub dirty_mask: u64,\n${deltaFields}\n}\n\npub fn ${snakeName}_dirty_mask(value: &${entity.name}Data) -> u64 { value.__dirty_mask }\n\npub fn take_${snakeName}_dirty_mask(value: &mut ${entity.name}Data) -> u64 { std::mem::take(&mut value.__dirty_mask) }\n\npub fn take_${snakeName}_delta(value: &mut ${entity.name}Data) -> Option<${entity.name}Delta> {\n    let dirty_mask = take_${snakeName}_dirty_mask(value);\n    if dirty_mask == 0 { return None; }\n    Some(${entity.name}Delta {\n        dirty_mask,\n${deltaValues}\n    })\n}` : "";
  return `${constants}${memberConstants ? `\n${memberConstants}` : ""}\n\n\
pub fn get_${snakeName}_number(value: &${entity.name}Data, field: u32) -> Option<f64> {\n\
    match field {\n${getters}\n        _ => None,\n    }\n\
}\n\n\
pub fn set_${snakeName}_number(value: &mut ${entity.name}Data, field: u32, number: f64) -> Result<(), &'static str> {\n\
    match field {\n${setters}\n        _ => Err("unknown native ${entity.name} field"),\n    }\n\
}${dirtyAccessors}`;
}

function renderRustVariantAccessors(entity: NativeEntityModel): string {
  const snake = toNativeSnakeCase(entity.name);
  return `    pub fn as_${snake}(&self) -> Option<&${entity.name}Data> {\n\
        match self { Self::${entity.name}(value) => Some(value), _ => None }\n\
    }\n\n\
    pub fn as_${snake}_mut(&mut self) -> Option<&mut ${entity.name}Data> {\n\
        match self { Self::${entity.name}(value) => Some(value), _ => None }\n\
    }\n`;
}

function renderRustCreateMatch(schema: NativeSemanticModel, entity: NativeEntityModel): string {
  const fields = projectNativeEntityApi(schema, entity).fields;
  const values = new Map(fields.map((field, index) => [field.name, `read_${field.type}(values, ${index})?`]));
  const init = renderRustStructInit(schema, entity.name, values, 12);
  return `        ENTITY_TYPE_${toNativeScreamingSnakeCase(entity.name)} => {\n\
            if values.len() != ${fields.length} { return Err("native ${entity.name} create value count mismatch"); }\n\
            if read_u32(values, 0)? == 0 || read_u32(values, 1)? == 0 {\n\
                return Err("native Entity id and instanceId must be greater than zero");\n\
            }\n\
            Ok(NativeEntityData::${entity.name}(${init}))\n\
        },`;
}

function renderRustStructInit(
  schema: NativeSemanticModel,
  entityName: string,
  values: ReadonlyMap<string, string>,
  indent: number,
): string {
  const entity = schema.entities.find((candidate) => candidate.name === entityName);
  if (!entity) throw new Error(`unknown native entity ${entityName}`);
  const padding = " ".repeat(indent);
  const childPadding = " ".repeat(indent + 4);
  const lines: string[] = [];
  if (entity.replicated) {
    const mask = entity.fields.reduce((value, field) => field.memberId === undefined ? value : value | (1n << BigInt(field.memberId)), 0n);
    lines.push(`${childPadding}__dirty_mask: ${mask}u64,`);
  }
  if (entity.parent) {
    lines.push(`${childPadding}${toNativeSnakeCase(entity.parent)}: ${renderRustStructInit(schema, entity.parent, values, indent + 4)},`);
  }
  for (const field of entity.fields) {
    lines.push(`${childPadding}${toNativeSnakeCase(field.name)}: ${values.get(field.name)},`);
  }
  return `${entity.name}Data {\n${lines.join("\n")}\n${padding}}`;
}

function renderTypeScript(schema: NativeSemanticModel, entity: NativeEntityModel, options: ResolvedOptions): string {
  const api = projectNativeEntityApi(schema, entity);
  const fields = api.fields;
  const fieldConstants = fields.filter((field) => field.ownerName === entity.name)
    .map((field) => `  ${toNativePascalCase(field.name)}: ${field.fieldId},`).join("\n");
  const fieldTypes = `export const ${api.fieldTableName} = {\n${fieldConstants}\n} as const;\n\nexport type ${api.fieldTableName} = typeof ${api.fieldTableName}[keyof typeof ${api.fieldTableName}];`;
  const memberConstants = fields.filter((field) => field.ownerName === entity.name && field.memberId !== undefined)
    .map((field) => `  ${toNativePascalCase(field.name)}: ${field.memberId},`).join("\n");
  const memberTypes = memberConstants ? `\n\nexport const Native${entity.name}Member = {\n${memberConstants}\n} as const;\n\nexport type Native${entity.name}Member = typeof Native${entity.name}Member[keyof typeof Native${entity.name}Member];` : "";
  const args = fields.map((field) => `  ${field.name}${field.defaultValue === undefined ? "" : "?"}: number;`).join("\n");
  const values = fields.map((field) => field.defaultValue === undefined
    ? `      args.${field.name},`
    : `      args.${field.name} ?? ${field.defaultValue},`).join("\n");
  const properties = fields.map((field) => {
    const setter = field.readonly ? "" : `\n  set ${field.name}(value: number) {\n    NativeOps.EntitySetNumber(this.Handle, ${field.fieldId}, value);\n  }\n`;
    return `  get ${field.name}(): number {\n    return NativeOps.EntityGetNumber(this.Handle, ${field.fieldId});\n  }\n${setter}`;
  }).join("\n");
  if (api.lifecycle === "handle") {
    return renderTypeScriptHandle(entity, api, args, values, properties, fieldTypes + memberTypes, options);
  }
  return `${options.banner}\n\n\
import { NativeOps } from "./NativeOps";\n\
import { Component } from "${options.componentBaseImport}";\n\
import { component } from "${options.componentDecoratorImport}";\n\n\
${fieldTypes}${memberTypes}\n\n\
export interface ${api.createArgsName} {\n${args}\n}\n\n\
@component()\n\
export class ${api.refName} extends Component<[args: ${api.createArgsName}]> {\n\
  private nativeHandle = 0;\n\n\
  get Handle(): number {\n\
    if (this.nativeHandle === 0) throw new Error("native ${entity.name} handle is not alive");\n\
    return this.nativeHandle;\n\
  }\n\n\
  protected override Awake(args: ${api.createArgsName}): void {\n\
    this.nativeHandle = NativeOps.EntityCreate(${entity.typeId}, new Float64Array([\n${values}\n    ]));\n\
  }\n\n\
${properties}\
  protected override OnDestroy(): void {\n\
    if (this.nativeHandle === 0) return;\n\
    NativeOps.EntityDestroy(this.nativeHandle);\n\
    this.nativeHandle = 0;\n\
  }\n\
}\n`;
}

function renderTypeScriptHandle(
  entity: NativeEntityModel,
  api: ReturnType<typeof projectNativeEntityApi>,
  args: string,
  values: string,
  properties: string,
  fieldTypes: string,
  options: ResolvedOptions,
): string {
  return `${options.banner}\n\n\
import { NativeOps } from "./NativeOps";\n\n\
${fieldTypes}\n\n\
export class ${api.refName} {\n\
  private nativeHandle: number;\n\n\
  private constructor(handle: number) {\n\
    this.nativeHandle = handle;\n\
  }\n\n\
  static Create(args: ${api.createArgsName}): ${api.refName} {\n\
    return new ${api.refName}(NativeOps.EntityCreate(${entity.typeId}, new Float64Array([\n${values}\n    ])));\n\
  }\n\n\
  get Handle(): number {\n\
    if (this.nativeHandle === 0) throw new Error("native ${entity.name} handle is not alive");\n\
    return this.nativeHandle;\n\
  }\n\n\
${properties}\n\
  Dispose(): void {\n\
    if (this.nativeHandle === 0) return;\n\
    NativeOps.EntityDestroy(this.nativeHandle);\n\
    this.nativeHandle = 0;\n\
  }\n\
}\n\n\
export interface ${api.createArgsName} {\n${args}\n}\n`;
}

function rustFieldPath(root: string, field: NativeProjectedEntityField): string {
  return `${root}.${field.rustPath.join(".")}`;
}

function renderRustSetter(entity: NativeEntityModel, field: NativeProjectedEntityField): string {
  const target = rustFieldPath("value", field);
  if (field.type === "f32") {
    return wrapDirtyAssignment(entity, field, target, `number as f32`, `if !number.is_finite() || number < f32::MIN as f64 || number > f32::MAX as f64 { return Err("native ${entity.name} field ${field.name} must be a finite f32"); }`);
  }
  const ranges: Record<string, readonly [string, string, string]> = {
    u32: ["0.0", "u32::MAX as f64", "u32"],
    i32: ["i32::MIN as f64", "i32::MAX as f64", "i32"],
    i8: ["i8::MIN as f64", "i8::MAX as f64", "i8"],
  };
  const range = ranges[field.type];
  if (!range) throw new Error(`unsupported native setter field type ${field.type}`);
  const [min, max, type] = range;
  return wrapDirtyAssignment(entity, field, target, `number as ${type}`, `if !number.is_finite() || number.fract() != 0.0 || number < ${min} || number > ${max} { return Err("native ${entity.name} field ${field.name} must be ${field.type}"); }`);
}

function nativeRustFieldType(type: NativeProjectedEntityField["type"]): string {
  const types: Record<NativeProjectedEntityField["type"], string> = {
    u32: "u32",
    i32: "i32",
    i8: "i8",
    f32: "f32",
  };
  const result = types[type];
  if (!result) throw new Error(`unsupported native Rust field type ${type}`);
  return result;
}

function wrapDirtyAssignment(entity: NativeEntityModel, field: NativeProjectedEntityField, target: string, converted: string, validation: string): string {
  const assign = field.memberId === undefined
    ? `${target} = converted;`
    : `if ${target} != converted { ${target} = converted; value.__dirty_mask |= 1u64 << ${field.memberId}; }`;
  return `${validation} let converted = ${converted}; ${assign}`;
}
