import assert from "node:assert/strict";
import test from "node:test";

import { assertValidNativeWorkspace } from "@tiangz/native-language-core";
import { generateNativeFiles } from "../dist/index.js";

const schema = assertValidNativeWorkspace([
  {
    uri: "Entity.native",
    text: `namespace demo;
abstract entity Entity {
  readonly id: u32;
  readonly instanceId: u32;
}
`,
  },
  {
    uri: "Unit.native",
    text: `namespace demo;
@typeId(1)
@component
@replicated
entity Unit extends Entity {
  @memberId(1)
  @hot
  x: f32 = 0;
}
`,
  },
  {
    uri: "Numeric.native",
    text: `namespace demo;
@typeId(2)
@replicated
entity Numeric extends Entity {
  @memberId(1)
  currentHp: i32 = 100;
}
`,
  },
  {
    uri: "NativeOps.native",
    text: `namespace native;
op EntityCreate(entityType: u32, values: f64[]): u32;
op EntityDestroy(handle: u32): void;
op EntityGetNumber(handle: u32, field: u32): f64;
op EntitySetNumber(handle: u32, field: u32, value: f64): void;
`,
  },
]);

test("generates deterministic in-memory files without project I/O", () => {
  const files = generateNativeFiles(schema);
  assert.deepEqual(files.map((file) => file.relativePath), [
    "src/generated/native_data.rs",
    "src/generated/native_ops.rs",
    "src/generated/native_ops_bootstrap.js",
    "app/generated/model/native/NativeOps.ts",
    "app/generated/model/native/NativeUnitRef.ts",
    "app/generated/model/native/NativeNumericRef.ts",
  ]);
  assert.equal(files[0].format, "rust");
  assert.ok(files.every((file) => file.content.startsWith("// Generated by tools/codegen_native_data.mjs. Do not edit.")));
});

test("generates different lifecycle APIs for components and standalone handles", () => {
  const files = generateNativeFiles(schema);
  const unit = files.find((file) => file.relativePath.endsWith("NativeUnitRef.ts"))?.content ?? "";
  const numeric = files.find((file) => file.relativePath.endsWith("NativeNumericRef.ts"))?.content ?? "";

  assert.match(unit, /extends Component/);
  assert.match(unit, /protected override Awake/);
  assert.match(unit, /TrackNativeRefCreated\("Unit"\)/);
  assert.match(unit, /TrackNativeRefDestroyed\("Unit"\)/);
  assert.doesNotMatch(unit, /static Create/);
  assert.doesNotMatch(unit, /Dispose\(\)/);

  assert.match(numeric, /static Create/);
  assert.match(numeric, /Dispose\(\)/);
  assert.match(numeric, /TrackNativeRefCreated\("Numeric"\)/);
  assert.match(numeric, /TrackNativeRefDestroyed\("Numeric"\)/);
  assert.doesNotMatch(numeric, /extends Component/);
  assert.match(numeric, /CurrentHp: 3/);
  assert.match(numeric, /NativeNumericMember/);
  assert.match(numeric, /CurrentHp: 1/);
  const rust = files.find((file) => file.relativePath.endsWith("native_data.rs"))?.content ?? "";
  const ops = files.find((file) => file.relativePath.endsWith("NativeOps.ts"))?.content ?? "";
  assert.match(ops, /NativeRefMetrics\(\): NativeRefMetrics/);
  assert.match(rust, /pub\(crate\) __dirty_mask: u64/);
  assert.match(rust, /NUMERIC_MEMBER_CURRENT_HP: u32 = 1/);
  assert.match(rust, /pub\(crate\) __member_revisions: \[u64; 64\]/);
  assert.match(rust, /pub struct NumericDelta/);
  assert.match(rust, /pub revision: u64/);
  assert.match(rust, /pub current_hp: Option<i32>/);
  assert.match(rust, /peek_numeric_delta/);
  assert.match(rust, /ack_numeric_delta/);
  assert.doesNotMatch(rust, /take_numeric_delta/);
  assert.match(rust, /value\.__dirty_mask \|= 1u64 << 1/);
  assert.match(rust, /value\.__member_revisions\[1\] = value\.__revision/);
  assert.match(rust, /__dirty_mask: 0u64/);
  assert.match(rust, /pub struct UnitHotData/);
  assert.match(rust, /pub x: f32/);
  assert.match(rust, /pub struct UnitColdData/);
  assert.match(rust, /pub id: u32/);
  assert.match(rust, /pub struct UnitSplitData/);
  assert.match(rust, /impl From<UnitData> for UnitSplitData/);
  assert.match(rust, /pub enum NativePoolLocation/);
  assert.match(rust, /pub struct NativeEntityPools/);
  assert.match(rust, /pub fn get_unit_hot\(/);
  assert.match(rust, /pub fn get_unit_cold\(/);
  assert.match(rust, /pub fn get_unit_parts\(/);
  assert.match(rust, /pub fn get_unit_split_number\(/);
  assert.match(rust, /pub fn set_unit_split_number\(/);
  assert.match(rust, /pub fn peek_unit_split_delta\(/);
  assert.match(rust, /pub fn ack_unit_split_delta\(/);
  assert.match(rust, /pub fn estimated_capacity_bytes\(/);
});

test("supports caller-owned output paths and generated banner", () => {
  const files = generateNativeFiles(schema, {
    generatedBy: "my-game/native-codegen",
    typeScriptRoot: "generated/native",
  });
  assert.ok(files.some((file) => file.relativePath === "generated/native/NativeOps.ts"));
  assert.ok(files.every((file) => file.content.startsWith("// Generated by my-game/native-codegen. Do not edit.")));
});
