import assert from "node:assert/strict";
import test from "node:test";

import { assertValidNativeWorkspace } from "@tiangz/native-language-core";
import { generateNativeFiles } from "../dist/index.js";

const schema = assertValidNativeWorkspace([
  {
    uri: "Entity.native",
    text: `namespace demo;
abstract entity Entity {
  readonly id: u32;
  readonly instanceId: u32;
}
`,
  },
  {
    uri: "Unit.native",
    text: `namespace demo;
@typeId(1)
@component
@replicated
entity Unit extends Entity {
  @memberId(1)
  @hot
  x: f32 = 0;
}
`,
  },
  {
    uri: "Numeric.native",
    text: `namespace demo;
@typeId(2)
@replicated
entity Numeric extends Entity {
  @memberId(1)
  currentHp: i32 = 100;
}
`,
  },
  {
    uri: "NativeOps.native",
    text: `namespace native;
op EntityCreate(entityType: u32, values: f64[]): u32;
op EntityDestroy(handle: u32): void;
op EntityGetNumber(handle: u32, field: u32): f64;
op EntitySetNumber(handle: u32, field: u32, value: f64): void;
op NumericGet(handle: u32, numericType: u32): i64;
op NumericSet(handle: u32, numericType: u32, value: i64): bool;
`,
  },
]);

test("generates deterministic in-memory files without project I/O", () => {
  const files = generateNativeFiles(schema);
  assert.deepEqual(files.map((file) => file.relativePath), [
    "src/generated/native_data.rs",
    "src/generated/native_ops.rs",
    "src/generated/native_ops_bootstrap.js",
    "app/generated/model/native/NativeOps.ts",
    "app/generated/model/native/NativeUnitRef.ts",
    "app/generated/model/native/NativeNumericRef.ts",
  ]);
  assert.equal(files[0].format, "rust");
  assert.ok(files.every((file) => file.content.startsWith("// Generated by tools/codegen_native_data.mjs. Do not edit.")));
});

test("generates different lifecycle APIs for components and standalone handles", () => {
  const files = generateNativeFiles(schema);
  const unit = files.find((file) => file.relativePath.endsWith("NativeUnitRef.ts"))?.content ?? "";
  const numeric = files.find((file) => file.relativePath.endsWith("NativeNumericRef.ts"))?.content ?? "";

  assert.match(unit, /extends Component/);
  assert.match(unit, /protected override Awake/);
  assert.match(unit, /TrackNativeRefCreated\("Unit"\)/);
  assert.match(unit, /TrackNativeRefDestroyed\("Unit"\)/);
  assert.doesNotMatch(unit, /static Create/);
  assert.doesNotMatch(unit, /Dispose\(\)/);

  assert.match(numeric, /static Create/);
  assert.match(numeric, /Dispose\(\)/);
  assert.match(numeric, /TrackNativeRefCreated\("Numeric"\)/);
  assert.match(numeric, /TrackNativeRefDestroyed\("Numeric"\)/);
  assert.doesNotMatch(numeric, /extends Component/);
  assert.match(numeric, /CurrentHp: 3/);
  assert.match(numeric, /NativeNumericMember/);
  assert.match(numeric, /CurrentHp: 1/);
  const rust = files.find((file) => file.relativePath.endsWith("native_data.rs"))?.content ?? "";
  const ops = files.find((file) => file.relativePath.endsWith("NativeOps.ts"))?.content ?? "";
  assert.match(ops, /NativeRefMetrics\(\): NativeRefMetrics/);
  assert.match(rust, /pub\(crate\) __dirty_mask: u64/);
  assert.match(rust, /NUMERIC_MEMBER_CURRENT_HP: u32 = 1/);
  assert.match(rust, /pub\(crate\) __member_revisions: \[u64; 64\]/);
  assert.match(rust, /pub struct NumericDelta/);
  assert.match(rust, /pub revision: u64/);
  assert.match(rust, /pub current_hp: Option<i32>/);
  assert.match(rust, /peek_numeric_delta/);
  assert.match(rust, /ack_numeric_delta/);
  assert.doesNotMatch(rust, /take_numeric_delta/);
  assert.match(rust, /value\.__dirty_mask \|= 1u64 << 1/);
  assert.match(rust, /value\.__member_revisions\[1\] = value\.__revision/);
  assert.match(rust, /__dirty_mask: 0u64/);
  assert.match(rust, /pub struct UnitHotData/);
  assert.match(rust, /pub x: f32/);
  assert.match(rust, /pub struct UnitColdData/);
  assert.match(rust, /pub id: u32/);
  assert.match(rust, /pub struct UnitSplitData/);
  assert.match(rust, /impl From<UnitData> for UnitSplitData/);
  assert.match(rust, /pub enum NativePoolLocation/);
  assert.match(rust, /pub struct NativeEntityPools/);
  assert.match(rust, /pub fn get_unit_hot\(/);
  assert.match(rust, /pub fn get_unit_cold\(/);
  assert.match(rust, /pub fn get_unit_parts\(/);
  assert.match(rust, /pub fn get_unit_split_number\(/);
  assert.match(rust, /pub fn set_unit_split_number\(/);
  assert.match(rust, /pub fn peek_unit_split_delta\(/);
  assert.match(rust, /pub fn ack_unit_split_delta\(/);
  assert.match(rust, /pub fn estimated_capacity_bytes\(/);
});

test("supports caller-owned output paths and generated banner", () => {
  const files = generateNativeFiles(schema, {
    generatedBy: "my-game/native-codegen",
    typeScriptRoot: "generated/native",
  });
  assert.ok(files.some((file) => file.relativePath === "generated/native/NativeOps.ts"));
  assert.ok(files.every((file) => file.content.startsWith("// Generated by my-game/native-codegen. Do not edit.")));
});

test("generates lossless i64 op bindings as TypeScript bigint", () => {
  const files = generateNativeFiles(schema);
  const bootstrap = files.find((file) => file.relativePath.endsWith("native_ops_bootstrap.js"))?.content ?? "";
  const ops = files.find((file) => file.relativePath.endsWith("NativeOps.ts"))?.content ?? "";

  assert.match(bootstrap, /const i64 = \(value, name\)/);
  assert.match(bootstrap, /numericSet: \(handle, numericType, value\).*i64\(value, "value"\)/);
  assert.match(ops, /numericGet\(handle: number, numericType: number\): bigint/);
  assert.match(ops, /NumericSet\(handle: number, numericType: number, value: bigint\): boolean/);
});

test("generates a strict versioned persistence codec without transient fields", () => {
  const persistentSchema = assertValidNativeWorkspace([
    {
      uri: "Entity.native",
      text: `namespace demo;
abstract entity Entity { readonly id: u32; @transient readonly instanceId: u32; }
`,
    },
    {
      uri: "Item.native",
      text: `namespace demo;
@typeId(2)
@persistent(3)
entity Item extends Entity { configId: u32; count: u32 = 1; }
`,
    },
    { uri: "Ops.native", text: "namespace native; op EntityCreate(entityType: u32, values: f64[]): u32;" },
  ]);
  const files = generateNativeFiles(persistentSchema);
  const persistence = files.find((file) => file.relativePath.endsWith("NativeItemPersistence.ts"))?.content ?? "";
  assert.match(persistence, /schemaVersion: 3/);
  assert.match(persistence, /schema: "demo.Item"/);
  assert.match(persistence, /recordNamespace: "entity.demo.item"/);
  assert.match(persistence, /readonly id: number/);
  assert.doesNotMatch(persistence, /readonly instanceId: number/);
  assert.match(persistence, /Capture\(value: NativeItemRef\)/);
  assert.match(persistence, /persistence fields are incomplete/);
});

test("restricts generated repositories by persistence write mode", () => {
  const modeSchema = assertValidNativeWorkspace([
    {
      uri: "Entity.native",
      text: `namespace demo;
abstract entity Entity { readonly id: u32; @transient readonly instanceId: u32; }
`,
    },
    {
      uri: "Modes.native",
      text: `namespace demo;
@typeId(2)
@persistent(1)
entity Item extends Entity { count: u32 = 1; }
@typeId(3)
@persistent(1)
@queued
entity Position extends Entity { mapId: u32; }
@typeId(4)
@persistent(1)
@transactional
entity Wallet extends Entity { gold: u32; }
`,
    },
    { uri: "Ops.native", text: "namespace native; op EntityCreate(entityType: u32, values: f64[]): u32;" },
  ]);
  const files = generateNativeFiles(modeSchema);
  const persistenceOf = (name) => files.find((file) => file.relativePath.endsWith(`Native${name}Persistence.ts`))?.content ?? "";

  // 普通写法保持旧版本生成文本，避免下游仓库重新生成时出现无关差异。
  // Ordinary output keeps the previous text so downstream regeneration has no unrelated churn.
  const plain = persistenceOf("Item");
  assert.match(plain, /^import \{ DbProxyEntityRepository, utf8Decode, utf8Encode, type VersionedEntityCodec \} from "\.\.\/\.\.\/\.\.\/core\/public";$/m);
  assert.match(plain, /^\/\*\* 创建该Entity的通用DBProxy Repository；复杂查询和跨记录事务应另写领域Repository。 \/ Creates the generic DBProxy Repository; queries and cross-record transactions need a domain Repository\. \*\/\nexport function CreateNativeItemRepository\(processName: string\): DbProxyEntityRepository<NativeItemPersistenceSnapshot, NativeItemRef> \{\n  return new DbProxyEntityRepository\(NativeItemPersistenceCodec, processName\);\n\}$/m);
  assert.doesNotMatch(plain, /Queued|Transactional/);

  const queued = persistenceOf("Position");
  assert.match(queued, /import \{ DbProxyQueuedEntityRepository, utf8Decode/);
  assert.match(queued, /CreateNativePositionRepository\(processName: string\): DbProxyQueuedEntityRepository<NativePositionPersistenceSnapshot, NativePositionRef>/);
  assert.match(queued, /new DbProxyQueuedEntityRepository\(NativePositionPersistenceCodec, processName\)/);
  assert.match(queued, /@queued：只能排队写入/);
  assert.doesNotMatch(queued, /DbProxyEntityRepository|DbProxyTransactionalEntityRepository/);

  const transactional = persistenceOf("Wallet");
  assert.match(transactional, /import \{ DbProxyTransactionalEntityRepository, utf8Decode/);
  assert.match(transactional, /CreateNativeWalletRepository\(processName: string\): DbProxyTransactionalEntityRepository<NativeWalletPersistenceSnapshot, NativeWalletRef>/);
  assert.match(transactional, /@transactional：只能通过事务写入/);
  assert.doesNotMatch(transactional, /DbProxyEntityRepository|DbProxyQueuedEntityRepository/);

  // 编解码部分与写法无关。 / The codec is independent of the write mode.
  for (const content of [plain, queued, transactional]) {
    assert.match(content, /schemaVersion: 1,/);
    assert.match(content, /persistence fields are incomplete/);
  }
});
